spring:
  mail:
    host: smtp.gmail.com
    username: vutuananh0405@gmail.com
    password: zjhcsmvnjlmughtx
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true